version: "3"

services:
  mongo:
    image: mongo:latest
    hostname: scraper-mongo
    ports:
      - "27017:27017"
    networks:
      - scraper-compose-network
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    hostname: redis
    networks:
      - scraper-compose-network
networks:
  scraper-compose-network:
    driver: bridge
