version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    networks:
      - scraper-compose-network
  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    hostname: torproxy
    restart: always
    ports:
      - 9050:9050
      - 9051:9051
      - 8118:8118
    environment:
      PASSWORD: PASSWORD
    networks:
      - scraper-compose-network
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
       - "3308:3306"
    networks:
      - scraper-compose-network
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    hostname: redis
    networks:
      - scraper-compose-network
networks:
  scraper-compose-network:
    driver: bridge
