apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-0
  labels:
    app: mongo-0
spec:
  ports:
    -
      port: 27017
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1
  labels:
    app: mongo-1
spec:
  ports:
    -
      port: 27017
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-2
  labels:
    app: mongo-2
spec:
  ports:
    -
      port: 27017
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-2
  type: LoadBalancer

