apiVersion: v1
kind: Service
metadata:
  name: mongo-0
  labels:
    app: mongo
spec:
  ports:
    -
      port: 27017
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1
  labels:
    app: mongo
spec:
  ports:
    -
      port: 27017
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-2
  labels:
    app: mongo
spec:
  ports:
    -
      port: 27017
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-2
  type: LoadBalancer

---
apiVersion: batch/v1
kind: Job
metadata:
  name: replset-scripte
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 200
      containers:
        - name: replset-scripte
          image: simo25docker/replset-scripte
          command: ['sh', '-c',"chmod +x setup.sh;./setup.sh"]


      restartPolicy: Never

