---
apiVersion: batch/v1
kind: Job
metadata:
  name: replset-scripte
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 200
      containers:
        - name: replset-scripte
          image: simo25docker/replset-scripte
          command: ['sh', '-c',"chmod +x setup.sh;./setup.sh"]


      restartPolicy: Never
