#
# ---- Base Node ----
FROM node:alpine3.10 AS base

RUN apk add --no-cache tini udev ttf-freefont chromium git

WORKDIR /job
COPY package.json /job
COPY yarn.lock /job
RUN ls
RUN yarn install

ENV PUPPETEER_CHROMIUM_REVISION '80.0.3987.0'
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser

CMD yarn start:dev
