apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-scraper-amzone
spec:
  selector:
    matchLabels:
      service-name: api-scraper-amzone
  replicas: 2
  template:
    metadata:
      labels:
        service-name: api-scraper-amzone
    spec:
      containers:
        - name: api-scraper-amzone
          image: simo25docker/api-scraper
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-scraper-amzone
  labels:
    app: api-scraper-amzone
    service-name: api-scraper-amzone
spec:
  type: LoadBalancer
  ports:
    - name: apiscraper
      port: 3000
      targetPort: 3000
  selector:
    service-name: api-scraper-amzone
