apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-scraper
  labels:
    service-name: api-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      service-name: api-scraper
  template:
    metadata:
      name: api-scraper
      labels:
        service-name: api-scraper
    spec:
      containers:
        - name: api-scraper
          image: simo25docker/api-scraper
          env:
            - name: JOB
              value: "scrapeMicroservice"
            - name: LEVEL
              value: "debug"
          ports:
            - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: api-scraper
  labels:
    app: api-scraper
    service-name: api-scraper
spec:
  type: LoadBalancer
  ports:
    - name: apiscraper
      port: 3000
      targetPort: 3000
  selector:
    service-name: api-scraper
