apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-scraper-amazon
spec:
  selector:
    matchLabels:
      service-name: api-scraper-amazon
  replicas: 2
  template:
    metadata:
      labels:
        service-name: api-scraper-amazon
    spec:
      containers:
        - name: api-scraper-amazon
          image: simo25docker/api-scraper
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-scraper-amazon
  labels:
    app: api-scraper-amazon
    service-name: api-scraper-amazon
spec:
  type: NodePort
  ports:
    - name: apiscraper
      port: 3000
      targetPort: 3000
  selector:
    service-name: api-scraper-amazon
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-scraper
  annotations:
    nginx.ingress.kubernetes.io/app-root: "/*"
spec:
  rules:
  - http:
     paths:
      - path: /api/v1
        backend:
          serviceName: api-scraper-amazon
          servicePort: 3000
