apiVersion: v1
kind: Service
metadata:
  name: redis-0
  labels:
    app: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-1
  labels:
    app: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
  selector:
    statefulset.kubernetes.io/pod-name: redis-1
  type: LoadBalancer
