apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-scraper
spec:
  schedule: "*/10 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: job-scraper
                image: simo25docker/job-scraper
            restartPolicy: Never
