apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-scraper
spec:
  schedule: "*/10 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job-scraper
              image: simo25docker/job-scraper
          restartPolicy: Never

