apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-scraper
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job-scraper
              image: simo25docker/job-scraper
          restartPolicy: Never

