apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: scraper-microservice
  labels:
    service-name: scraper-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service-name: scraper-microservice
  template:
    metadata:
      name: scraper-microservice
      labels:
        service-name: scraper-microservice
    spec:
      containers:
        - name: scraper-microservice
          image: simo25docker/job-scraper
          env:
            - name: JOB
              value: "scrapeMicroservice"
            - name: LEVEL
              value: "debug"


---
apiVersion: v1
kind: Service
metadata:
  name: scraper-microservice
  labels:
    app: scraper-microservice
    service-name: scraper-microservice
spec:
  type: LoadBalancer
  ports:
    - name: microservice
      port: 5667
      targetPort: 5667
  selector:
    service-name: scraper-microservice
