apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 4369
      name: rabbitmq-epmd
    - port: 5672
      name: rabbitmq-main
    - port: 15672
      name: rabbitmq-management
    - port: 25672
      name: rabbitmq-management-ssl
  type: LoadBalancer
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        component: rabbitmq
    spec:
      containers:
        - image: rabbitmq
          name: rabbitmq
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672


