name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: node:alpine3.10 
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: simo25docker/job-scrape
        username: ${{ secrets.LOGIN_DOCKER }}
        password: ${{ secrets.PASSWORD_DOCKER }}
        registry: docker.pkg.github.com
        workdir: job-scraper        


